/*
CREACION DE LA BASE DE DATOS y SUS RESPECTIVAS TABLAS

FECHA: 24/09/2023
AUTOR: ANDREA TASAYCO
*/
DROP DATABASE IF EXISTS TIENDA;

CREATE DATABASE TIENDA
 character set "utf8mb4"
 collate "utf8mb4_0900_ai_ci";

USE TIENDA;
CREATE TABLE VENDEDORES (
IDVENDEDOR INTEGER PRIMARY KEY auto_increment,
NOMBRE VARCHAR(20) NOT NULL,
APELLIDO VARCHAR(20) NOT NULL ,
CORREO VARCHAR(20)
)COMMENT 'TABLA CON INFORMACIÓN DE VENDEDORES';

CREATE TABLE CATEGORIAS (
IDCATEGORIA INT PRIMARY KEY auto_increment,
CATEGORIA VARCHAR (50)
)COMMENT 'TABLA CATEGORIAS';

CREATE TABLE MEDIO_PAGO (
IDMEDIOPAGO INT PRIMARY KEY auto_increment,
DETALLE VARCHAR(20) 
)COMMENT 'TABLA MEDIO DE PAGO';

CREATE TABLE PRODUCTOS (
IDPRODUCTO INT PRIMARY KEY auto_increment,
CODIGO_SKU VARCHAR(50),
DESCRIPCION VARCHAR(50),
IDCATEGORIA INT,
PRECIO INT ,
STOCK INT,
FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIAS(IDCATEGORIA)
)COMMENT 'TABLA PRODUCTOS';

CREATE TABLE BOLETAS (
IDBOLETA INT PRIMARY KEY auto_increment,
IDVENDEDOR INT,
IDMEDIOPAGO INT,
FECHA DATETIME,
FOREIGN KEY (IDVENDEDOR) REFERENCES VENDEDORES(IDVENDEDOR),
FOREIGN KEY (IDMEDIOPAGO) REFERENCES MEDIO_PAGO(IDMEDIOPAGO)
)COMMENT 'TABLA CON INFORMACIÓN DE BOLETAS';

CREATE TABLE DETALLE_VENTAS (
IDDETALLEVENTA INT PRIMARY KEY auto_increment,
IDBOLETA INT,
IDPRODUCTO INT,
CANTIDAD INT,
FOREIGN KEY (IDBOLETA) REFERENCES BOLETAS(IDBOLETA),
FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(IDPRODUCTO)
)COMMENT 'TABLA DETALLE DE VENTAS';