/*
PROCEDIMIENTO PARA ACTUALIZAR MEDIO DE PAGO EN LA TABLA MEDIO_PAGO
call actualizar_medio_pago(IDMEDIOPAGO, DETALLE);

FECHA: 02/10/2023
AUTOR: KEVIN FLORES
*/
use TIENDA;

drop procedure if exists actualizar_medio_pago;
delimiter $$
CREATE PROCEDURE actualizar_medio_pago(
	IN _IDMEDIOPAGO INT,
    IN _DETALLE VARCHAR(20)
)
BEGIN
UPDATE MEDIO_PAGO
SET DETALLE = _DETALLE
WHERE IDMEDIOPAGO=_IDMEDIOPAGO;
END
$$