/*
PROCEDIMIENTO PARA MOSTRAR DETALLE DE VENTAS POR BOLETAS
call mostrar_detalle_venta(IDBOLETA)

FECHA: 02/10/2023
AUTOR: KEVIN FLORES
*/
use TIENDA;

drop procedure if exists mostrar_detalle_venta;
delimiter $$
CREATE PROCEDURE mostrar_detalle_venta(
    IN AUX INT
)
BEGIN
    SELECT BOLETAS.IDBOLETA,  FECHA, PRODUCTOS.CODIGO_SKU, DESCRIPCION, CATEGORIA, DETALLE_VENTAS.CANTIDAD, (PRECIO*CANTIDAD) as PRECIO_TOTAL, concat(VENDEDORES.NOMBRE, " ", VENDEDORES.APELLIDO) as VENDEDOR
    FROM DETALLE_VENTAS
    INNER JOIN PRODUCTOS ON DETALLE_VENTAS.IDPRODUCTO = PRODUCTOS.IDPRODUCTO
    INNER JOIN BOLETAS ON DETALLE_VENTAS.IDBOLETA = BOLETAS.IDBOLETA
    LEFT JOIN CATEGORIAS ON PRODUCTOS.IDCATEGORIA = CATEGORIAS.IDCATEGORIA
    LEFT JOIN VENDEDORES ON BOLETAS.IDVENDEDOR = VENDEDORES.IDVENDEDOR
    WHERE DETALLE_VENTAS.IDBOLETA = AUX;
END
$$