/*
PROCEDIMIENTO PARA ELIMINAR DETALLES DE VENTA EN LA TABLA DETALLE_VENTAS
call eliminar_detalle_venta(IDDETALLEVENTAS);

FECHA: 02/10/2023
AUTOR: KEVIN FLORES
*/
use TIENDA;

drop procedure if exists eliminar_detalle_venta;
delimiter $$
CREATE PROCEDURE eliminar_detalle_venta(
	IN _IDDETALLEVENTAS INT
)
BEGIN
DELETE
FROM DETALLE_VENTAS
WHERE IDDETALLEVENTAS = _IDDETALLEVENTAS;
END
$$